### PR TITLE
Rework auto config loop

### PR DESCRIPTION
**Pull request by andresmanelli**
- Remove intermediate variables when possible
 - Convert time-value tuples to lists at the start
 - Rename some variables to better understand the loops

### CODE REVIEW

**Comment by andresmanelli** [comment]
Hey @Fresher14 , I read the auto config function, and I would like to make some adjustments before merge. The logic is unchanged, but I renamed some variables, and merged some for loops to avoid doing it multiple times.

I have just two questions:
 - Why there is a range(2, ...) in the diff computation instead of range(1, ... ?
 - Why is the second point used to get the syncTime (and not the first)

I'm not saying that is wrong, I just didn't get that. Anyway thank you for the feature, I hope we can merge that soon !!

**Comment by andresmanelli** [comment]
Oh after this merge (if that's ok with you), you should rebase your branch to the lastest Toroid-io:master. Cheers

**Comment by Fresher14** [comment]
> Hey @Fresher14 , I read the auto config function, and I would like to make some adjustments before merge. The logic is unchanged, but I renamed some variables, and merged some for loops to avoid doing it multiple times.
> 
> I have just two questions:
> 
> * Why there is a range(2, ...) in the diff computation instead of range(1, ... ?
> * Why is the second point used to get the syncTime (and not the first)
> 
> I'm not saying that is wrong, I just didn't get that. Anyway thank you for the feature, I hope we can merge that soon !!

Hello. I don’t have the code under my eyes right now. As far as I remember the auto features evaluates fastest clock and thus first sample which is not aligned on clock compulsory must be skipped. Then it rounds all timing points to closest considering maximum 4x oversampling otherwise this would make output unusable, especially if exporting from a gate simulation. Hope this helps

**Comment by andresmanelli** [comment]
Ok!. So as I said, of you're ok with these changes, you can merge this and
then we can merge your PR. Thanks!

**Comment by Fresher14** [comment]
Honestly, I'm completely lost with GitHub. So, do your best and if I have to click somewhere, just tell me.

**Comment by andresmanelli** [comment]
Yes, you can do both, as you wish.

**Pull request closed without merging**
